import type { Metadata } from "next";
import { Inter, Metrophobic } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navbar/navigation";
import Footer from "@/components/footer/footer";
import ScrollToTopButton from "@/components/landing/scroll-to-top-button";

const inter = Inter({ subsets: ["latin"] });
const metrophobic = Metrophobic({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Starlly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Metrophobic&display=swap" rel="stylesheet" />
      </head>
      <body style={{fontFamily:"Metrophobic"}} suppressHydrationWarning={true}>
        <Navigation />
        <main >
          {children}
        </main>
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
